version: '3.8'
services:
  php-apache-environment:
    container_name: file-transfer
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8000:80
